const STRING_CONSTANTS = {

	INTERNAL_ERROR: 'Internal server error',
	NEW_USER_ADD: 'New user resistered succsessfully',
	EXISTING_EMAIL: 'Email already registered',
	EMAIL_NOT_EXISTED: 'Email does not exist',
	EMAIL_INVALID: 'Please enter valid email',
	LOGIN_SUCCESS: 'Login Successfully',
	INVALID_CREDENTIALS: 'Invalid User Credentials',
	OTP_SENT: 'OTP sent successfully on your email',
	OTP_VERIFIED: 'OTP verified successfully',
	OTP_EXPIRED: 'OTP expired',
	OTP_INVALID: 'Incorrect OTP',
	PASSWORD_UPDATED: 'Password updated successfully',
	PASSWORD_NOT_MATCH: 'Passwords do not match',
	CATEGORY_ADDED: 'New category added succsessfully',
	CATEGORY_EXIST: 'Category already exist',
	CATEGORY_LIST: 'List of categories',
	CATEGORY_UPDATE: 'Category updated succsessfully',
	CATEGORY_NOT_UPDATE: 'Unable to update category',
	CATEGORY_DELETE: 'Category deleted succsessfully',
	CATEGORY_NOT_DELETE: 'Unable to delete category',
	CATEGORY_ALREADY_DELETE: 'Category already deleted',
	SUB_CATEGORY_ADDED: 'New Sub-category added succsessfully',
	SUB_CATEGORY_EXIST: 'sub-category already exist',
	SUB_CATEGORY_LIST: 'List of sub-categories',
	SUB_CATEGORY_UPDATE: 'Sub-category updated succsessfully',
	SUB_CATEGORY_NOT_UPDATE: 'Unable to update sub-category',
	SUB_CATEGORY_DELETE: 'Sub-category deleted succsessfully',
	SUB_CATEGORY_NOT_DELETE: 'Unable to delete sub-category',
	SUB_CATEGORY_ALREADY_DELETE: 'Sub-category already deleted',
	BRAND_ADDED: 'Brand Added succsessfully',
	BRAND_EXIST: 'Brand already exist',
	BRAND_LIST: 'List of brands',
	BRAND_UPDATE: 'Brand updated succsessfully',
	BRAND_NOT_UPDATE: 'Unable to update brand',
	BRAND_DELETE: 'BRAND deleted succsessfully',
	BRAND_NOT_DELETE: 'Unable to delete brand',
	BRAND_ALREADY_DELETE: 'brand already deleted',
	/// AUTH VALIDATOR MASSAGE
	EMAIL_REQUIRED: 'Please enter email',
	PASWORD_REQUIRED: 'Please Enter Password',
	CONFIRM_PASWORD_REQUIRED: 'Please Enter Password',
	INVALID_PASSWORD: 'Please password must contain at least one uppercase letter, one number, one special character, and be at least 8 characters long',
	INVALID_CONFIRM_PASSWORD: 'Please confirm password must contain at least one uppercase letter, one number, one special character, and be at least 8 characters long',
	NAME_REQUIRE: 'Please enter name',
	COUNTRY_CODE_REQUIRE: 'Please enter country code',
	MOBILE_REQUIRE: 'Please Enter Mobile number',
	INVAILD_MOBILE: 'Please enter valid mobile number',
	ROLE_REQUIRE: 'Please enter role',
	OTP_REQUIRE: 'please enter OTP',
	OTP_INNCORRECT: 'Please enter a valid OTP',
	//Category MESSAGE

	CATEGORY_NAME_REQUIRE: 'Please enter category name',
	SUB_CATEGORY_NAME_REQUIRE: 'Please enter sub-category name',

	//Brand messages
	BRAND_NAME_REQUIRE: 'Please enter brand name',
	
};

module.exports = {
	STRING_CONSTANTS,
};
