const STRING_CONSTANTS = {

	INTERNAL_ERROR: 'Internal server error',
    NEW_USER_ADD: 'New user resistered succsessfully',
	EXISTING_EMAIL: 'Email already registered',
	EMAIL_NOT_EXISTED: 'Email does not exist',
	LOGIN_SUCCESS: 'Login Successfully',
	INVALID_CREDENTIALS: 'Invalid User Credentials',
	OTP_SENT: 'OTP sent successfully on your email',
	OTP_VERIFIED: 'OTP verified successfully',
	OTP_EXPIRED: 'OTP expired',
	OTP_INVALID: 'Incorrect OTP',
	PASSWORD_UPDATED: 'Password updated successfully',
	PASSWORD_NOT_MATCH: 'Passwords do not match',
	CATEGORY_ADDED: 'New category added succsessfully',
	CATEGORY_EXIST: 'Category already exist',
	CATEGORY_LIST: 'List of categories',
	CATEGORY_UPDATE: 'Category updated succsessfully',
	CATEGORY_NOT_UPDATE: 'Unable to update category',
	CATEGORY_DELETE: 'Category deleted succsessfully',
	CATEGORY_NOT_DELETE: 'Unable to delete category',
	CATEGORY_ALREADY_DELETE: 'Category already deleted',
	SUB_CATEGORY_ADDED: 'New Sub-category added succsessfully',
	SUB_CATEGORY_EXIST: 'sub-category already exist',
	SUB_CATEGORY_LIST: 'List of sub-categories',
	SUB_CATEGORY_UPDATE: 'Sub-category updated succsessfully',
	SUB_CATEGORY_NOT_UPDATE: 'Unable to update sub-category',
	SUB_CATEGORY_DELETE: 'Sub-category deleted succsessfully',
	SUB_CATEGORY_NOT_DELETE: 'Unable to delete sub-category',
	SUB_CATEGORY_ALREADY_DELETE: 'Sub-category already deleted',
	BRAND_ADDED: 'Brand Added succsessfully',
	BRAND_EXIST: 'Brand already exist',
	BRAND_LIST: 'List of brands',
	BRAND_UPDATE: 'Brand updated succsessfully',
	BRAND_NOT_UPDATE: 'Unable to update brand',
	BRAND_DELETE: 'BRAND deleted succsessfully',
	BRAND_NOT_DELETE: 'Unable to delete brand',
	BRAND_ALREADY_DELETE: 'brand already deleted',
};
module.exports = {
	STRING_CONSTANTS,
};
